### ISSUE TITLE
Red and white spots

### ISSUE THREAD

**Issue by 5p4ce** [positlabs/spark-lut-patch#1]
![IMG_6767](https://user-images.githubusercontent.com/6620583/65782543-2e2e5d80-e14e-11e9-9b84-bde99d601188.JPG)

Having a problem: There are areas on my filter, white and red ones.

**Comment by positlabs** [comment]
Have you disabled compression?

**Comment by yavadta** [comment]
i change CLAMP in FastColorLUT
mix 0,03
max 0,93

**Comment by positlabs** [comment]
That could work, but you should always disable compression on LUT textures. 
<img width="281" alt="Screen Shot 2019-09-27 at 1 01 37 PM" src="https://user-images.githubusercontent.com/1918844/65787498-142d5480-e127-11e9-9a2f-0311bcf74398.png">

**Comment by 5p4ce** [comment]
Found the problem ran the beta v66 version. And there was no option to disable compression. Thanks for the help anyways.
