### ISSUE TITLE
doubt about LUT settings

### ISSUE THREAD

**Issue by otaldonunes** [positlabs/spark-lut-patch#4]
Hi, how are you?

I had a question about the configuration of luts in lightroom, can I only change the colors of the base image? Or I can insert lightroom settings for sharpening, grainy and etc.

**Comment by varuogm** [comment]
Yes , maybe we can control those as well. I once got a blurry LUT by changing some settings.so i think its possible

**Comment by positlabs** [comment]
Sorry I didn't see this until now. LUTs can only be used for color modification. Sharpening, clarity, blur, noise, etc, all change the pixel locations so it ruins the color lookup and you get weird banding issues
